Fix a failing test.
The test was failing because the expected zero value was about 10^-6.
Which is still fine, so I downgraded the precision expectation.

Error message of the failing test (testFlatAngleOnTheEquator):
AssertionError: 1.2074182697257333e-06 != 0.0 within 7 places